### ISSUE TITLE
SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by Christian-B** [dieghernan/cff-validator#10] opened 2023-07-20 05:34 UTC
We have been using dieghernan/cff-validator@main for a while now.

However since 19 Jul 2023 we get:
Error in download.file("https://raw.githubusercontent.com/citation-file-format/citation-file-format/main/schema.json",  : 
  cannot open URL 'https://raw.githubusercontent.com/citation-file-format/citation-file-format/main/schema.json'
In addition: Warning message:
In download.file("https://raw.githubusercontent.com/citation-file-format/citation-file-format/main/schema.json",  :
  URL 'https://raw.githubusercontent.com/citation-file-format/citation-file-format/main/schema.json': status was 'SSL peer certificate or SSH remote key was not OK'

This also in github action that previously passed and where rerun.

**Comment by dieghernan** [comment] 2023-07-20 06:09
Hi @Christian-B 

That's odd, since the message refers to issues on the SSL certificate of the web where the schema is hosted, that is GitHub (¿?). I [re-runned my test actions](https://github.com/dieghernan/cff-validator/actions) and all are ok (except the one that is expected to give an error). I already run the action on a [fork of SpiNNaker/spinnaker_tools](https://github.com/dieghernan/spinnaker_tools/actions) and everything seems to be ok as well.

Can you re-run the actions and provide a link to the results?

**Comment by dieghernan** [comment] 2023-07-20 07:14
Hi @Christian-B 

This sould be fixed now in `main`, instead of downloading the schema (that was the root cause of the problem) I use now a version already shipped with the R cffr package (I am also the maintainer of that software).

I realized that the download of the schema was also troublesome for cffr some time ago, see https://github.com/ropensci/cffr/issues/33

https://github.com/dieghernan/cff-validator/blob/176e7e82965b0211e874c3bbb5142905fcd68038/action.yml#L115-L116

Please do let me know if you still see the error

**Comment by Christian-B** [comment] 2023-07-20 09:18
Thank you for the quick reply.

I can confirm that in multiple of our repositories this now works.
________________________________

**Closed** 2023-07-20 13:02 UTC
